version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: pro2019
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 9999:80
